# This is a basic workflow to help you get started with Actions

name: reindexator

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  reindexator:
    runs-on: ubuntu-latest
    steps:
      - uses: fjogeleit/http-request-action@master
        id: reindexator
        with:
          url:   ${{ secrets.CORPUS_URL }}
          method: 'POST'
          username: ${{ secrets.CORPUS_USER }}
          password: ${{ secrets.CORPUS_PASSWORD }}
