# This is a basic workflow to help you get started with Actions

name: reindexator

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  refresher:
    runs-on: ubuntu-latest
    steps:
      - uses: fjogeleit/http-request-action@master
        id: reindexator
        with:
          url:   ${{ secrets.CORPUS_URL_REFRESH}} 
          method: 'POST'
          username: ${{ secrets.CORPUS_USER }}
          password: ${{ secrets.CORPUS_PASSWORD }}
      - uses: dawidd6/action-send-mail@v2
        id: send_mail
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: Refresh of ${{github.repository}} completed successfully!
          # Literal body:
          body: ${{steps.reindexator.outputs.response}}
          to: ${{secrets.EMAIL_LIST}}
          from: Mansi corpus
          content_type: text/html
          timeout:  120000
  reindexator:
    runs-on: ubuntu-latest
    steps:
      - uses: fjogeleit/http-request-action@master
        id: reindexator
        with:
          url:   ${{ secrets.CORPUS_URL_REINDEX }}
          method: 'POST'
          username: ${{ secrets.CORPUS_USER }}
          password: ${{ secrets.CORPUS_PASSWORD }}
      - uses: dawidd6/action-send-mail@v2
        id: send_mail
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: Build job of ${{github.repository}} completed successfully!
          # Literal body:
          body: ${{steps.reindexator.outputs.response}}
          to: ${{secrets.EMAIL_LIST}}
          from: Mansi corpus
          content_type: text/html
